# Generated by Django 5.2.17 on 2026-09-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(verbose_name='AI回答')),
                ('source', models.CharField(default='ai', max_length=50, verbose_name='信息来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
