# Generated by Django 5.2.17 on 2026-09-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('phase', models.CharField(max_length=20)),
                ('publish_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
