# Generated by Django 5.2.17 on 2026-09-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
    ]
